#!/bin/bash

# A simple script to display wifi name
# 'ssid -i' = with icon, 'ssid' = text only
# Cheers!
# Addy

SSID_NAME=$(LANG=C nmcli -t -f active,ssid dev wifi | grep '^yes:' | cut -d: -f2)

if [[ "${SSID_NAME}" != "" ]]; then
	if  [[ $1 = "-i" ]]; then
    echo "  ${SSID_NAME}"
	else
    echo "${SSID_NAME}"
	fi
else
echo "Not Connected"
fi

exit
